name: Jorge Ramos
markdown: kramdown
collections:
    category:
        output: true
defaults:
    -
        scope:
            path: ""
            type: category
        values:
            layout: "category"
